# Generated by Django 4.2.1 on 2024-03-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Assuntos',
            },
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bancas',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Concursos',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Órgãos',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250)),
                ('escolaridade', models.CharField(choices=[('M', 'Médio'), ('S', 'Superior')], default='M', max_length=1)),
                ('ano', models.IntegerField(null=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banca_prova', to='quiz.banca')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_prova', to='quiz.cargo')),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concurso_prova', to='quiz.concurso')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgao_prova', to='quiz.orgao')),
            ],
            options={
                'verbose_name_plural': 'Provas',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('texto1', models.TextField(blank=True, null=True)),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='quiz_imgs/')),
                ('texto2', models.TextField(blank=True, null=True)),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='quiz_imgs/')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assunto_questao', to='quiz.assunto')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_questao', to='quiz.disciplina')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova_questao', to='quiz.prova')),
            ],
            options={
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(blank=True, max_length=3, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='quiz_imgs/')),
                ('correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questao_resposta', to='quiz.questao')),
            ],
            options={
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.AddField(
            model_name='assunto',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_assunto', to='quiz.disciplina'),
        ),
    ]
